### ISSUE TITLE
logicmonitor_data_sdk.api.response_interface not found

### ISSUE THREAD

**Issue by louspringer** [logicmonitor/logicmonitor_data_sdk_py#22]
[The Python Data SDK library for LogicMonitor](https://logicmonitor-data-sdk-py.readthedocs.io/en/latest/#python-data-sdk-library-for-logicmonitor) has an example importing a `response_interface` 

```
...
from logicmonitor_data_sdk.api.response_interface import ResponseInterface
...
```

This example fails with the message `ImportError: cannot import name 'ResponseInterface' from 'logicmonitor_data_sdk.api.response_interface' (/home/faction/.local/lib/python3.8/site-packages/logicmonitor_data_sdk/api/response_interface.py)`

Has `response_interface` moved?

**Comment by anubhav6663** [comment]
Can you please try to upgrade the logicmonitor_data_sdk package. 
commands for the same: 
`pip install --upgrade logicmonitor_data_sdk`
If this doesn't work try uninstalling and reinstall the same.

**Comment by louspringer** [comment]
That did it, thanks!
